### ISSUE TITLE
feat: allow accounts to submit multiple, partial votes

### ISSUE THREAD

**Issue by mds1** [ScopeLift/flexible-voting#13]
_This is intended as a discussion, not something that will definitely be implemented._

Using arbitrary `GOV` token and  Aave receipt token `aGOV` for the below.

## Problem

Currently, aGOV token holders vote until `X` blocks before the proposal deadline (the `CAST_VOTE_WINDOW`), to leave time for the rolled up vote to be cast. Block numbers are used because that's how the OZ governor [tracks proposals](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b2970b96e5e2be297421cd7690e3502e49f7deff/contracts/governance/Governor.sol#L38-L43). This has a few issues:

1. It doesn't work as cleanly on L2s or chains like Avalanche where block production is not at a fixed rate. You have fewer guarantees of how much time will remain to cast the rollup vote.
    1. On chains like Optimisim [where](https://community.optimism.io/docs/developers/build/differences/#block-numbers-and-timestamps) `1 transaction == 1 block`, an attacker can see when `CAST_VOTE_WINDOW` is, and once it's reached, spam transactions to accelerate the block number and end proposal voting sooner, to prevent the rolled up flexible vote from being cast. (Note that in the case of Optimism, once Bedrock is released, it [will be](https://community.optimism.io/docs/developers/build/differences/#address-aliasing-2) a fixed 2 second block time, but the problem still exists for other chains)
2. Voter UX takes a hit, so flexible voting isn't "free" to implement:
    1. Users have no guarantee someone will actually cast their rollup vote unless they send it themselves, so must pay attention after voting to then submit the rolled up transaction if they want to guarantee their vote is cast.
    2. Users have a smaller voting window (i.e. less time to research a proposal and vote on it) when voting with `aGOV` compared to `GOV` voters.
3. Tracking proposal vote counts for an ongoing proposal now lags: Expressed `aGOV` votes are not cast until near the deadline, so other voters have less information about existing votes, and there may be a large, last minute change once the rollup vote is cast. You can solve this with a UI/data layer that aggregates across all flexible voting contracts, but (1) that's complex, and (2) there's no guarantee those votes will all be cast.

## Solution

Modify `GovernorCountingFractional` so accounts can vote multiple times, but cannot re-cast votes. Assuming I have 10 GOV tokens, here are four scenarios illustrating UX that is possible (ignoring the `abstain` option for simplicity in the examples):

1. Casting a single yes vote for all 10 tokens
2. Casting an initial vote of 7 yes votes and a second vote of 3 no votes
3. Casting an initial vote of 7 tokens, split into 5 yes and 2 no, a second vote of 3 tokens split into 1 yes and 2 no.
4. Casting an initial vote of 5 tokens, split into 4 yes and 1 no, a second vote of 3 tokens split into 1 yes and 2 no, a third vote of 2 tokens split into 0 yes and 2 no.

As an individual, you likely would never do anything except the first bullet. But this is useful for flexible voting to mitigate all of the above issues. 

This solution does not mean you introduce the ability to change votes after they've been cast—once an initial vote with a weight of `n` tokens is cast, you cannot re-vote with those `n` tokens. Once my initial vote of 7 tokens has been cast, I can only submit 3 more votes. I cannot replace/update those 7 votes (unless we want to allow that, but feels like a separate issue, and I don't think we want to allow that).

This does mean voting is more expensive and has an cold extra storage write in the governor (to subtract a user's remaining vote weight), but the contract (e.g. AToken) no longer needs to write the vote weight since it can just pass it on to the governor, so you save a warm storage write there. So it will still be more expensive, but I think this is worth it, especially because it mitigates an attack vector. (Granted, isn't that attack vector currently present in a different form? I don't think I've heard this discussed much, but either way I don't think we should introduce it in a second format)

From an implementation perspective I don't think it should be too complicated:
- Pools such as `FractionalPool` no longer need `CAST_VOTE_WINDOW`
- `GovernorCountingFractional` now tracks how many tokens of a users voting weight have been used. 

There is very likely other implementation details, and perhaps downsides, that I'm missing that need to be discussed

**Comment by davidlaprade** [comment]
Super interesting idea! Sorry for the delay responding to this.

Just to clarify, I think what you're suggesting is that the pool would operate something like this (using an aToken as the example pool):

1. some user has an aUNI balance and wants to vote on a UNI proposal
1. that user calls `aUNI.expressVote(proposalId, VoteType.Whatever)` for that proposal
1. **within that same function call**, aUNI determines the voter's weight based on their balance at the proposal timestamp, then aUNI immediately calls `governor.castVoteWithReasonAndParams(...)` passing in the votes just for that user
1. the governor records those votes for aUNI
1. repeat steps 1-4 each time an aUNI holder wants to vote 

Is that right?

If so, I think this sounds like a really interesting feature, it would solve the problems that you mention, and I don't think it'd be that hard to support it.

That said, I'm not sure every pool would want to allow users to cast their votes at the same time they express them, as that would make vote expression substantially more costly. But some might, and I think we want to be able to give 3rd party integrations as many options as possible.

**Comment by mds1** [comment]
> Is that right?

Yep that is right!

> That said, I'm not sure every pool would want to allow users to cast their votes at the same time they express them, as that would make vote expression substantially more costly. But some might, and I think we want to be able to give 3rd party integrations as many options as possible.

I just edited my original comment, it wouldn't be _too_ much more costly because you do remove one storage write and replace it with a new. However it is worth benchmarking. 

Two workarounds to that are:
1. Give users the option to either (1) pass on their vote immediately, or (2) store it locally and the next person to vote pass on passes on all votes. Or,
2. Give users the option to either (1) pass on their vote immediately, or (2) store it locally and there still exists a concept of a rollup vote that someone needs to submit after the `CAST_VOTE_WINDOW`

But those of course add complexity, and I'm becoming of the opinion that gas costs shouldn't drive decisions like this _too much_, as this design may be in place for a long time, and gas costs are trending down with e.g. L2s, and an extra 20k gas is only ~$0.60 on mainnet and significantly less on L2

**Comment by rsolari** [comment]
I wanted to register my support for this idea. I was talking about it with @apbendi earlier today. My view is that the benefits of partial voting outweigh the costs here.

**Comment by mds1** [comment]
This is now implemented, per https://github.com/ScopeLift/flexible-voting/pull/31
