### ISSUE TITLE
Upstream changes to Aave v3 to make it more extensible

### ISSUE THREAD

**Issue by davidlaprade** [ScopeLift/flexible-voting#16]
We already did this here: https://github.com/aave/aave-v3-core/pull/726

Other functions we should update:
* `aToken.burn` to [make it public](https://github.com/ScopeLift/flexible-voting/pull/11/files#r1020441171) (rather than external)
* [`aToken.intialize`](https://github.com/aave/aave-v3-core/blob/f3e037b3638e3b7c98f0c09c56c5efde54f7c5d2/contracts/protocol/tokenization/AToken.sol#L53-L62) to [make it virtual](https://github.com/ScopeLift/flexible-voting/pull/21/files#r1052489548) (so that we can override flex voting aTokens to self-delegate during initialization)
* [`aToken._transfer`](https://github.com/aave/aave-v3-core/blob/f3e037b3638e3b7c98f0c09c56c5efde54f7c5d2/contracts/protocol/tokenization/AToken.sol#L206-L211) to [make it virtual](https://github.com/ScopeLift/flexible-voting/pull/21#discussion_r1051191099) (so that we can checkpoint during both transfer and transferFrom with the same code)

**Comment by davidlaprade** [comment]
I realized this morning that we don't need to make `aToken.burn()` public to do what we want. See https://github.com/ScopeLift/flexible-voting/pull/21/commits/ffc286730a460d64d763e9075adb853a4faf1046 for a better solution that didn't require any Aave changes.

I pushed a PR to make the other two changes: https://github.com/aave/aave-v3-core/pull/774

**Comment by apbendi** [comment]
@davidlaprade should we close this now that our PR has been merged by Aave?
