### ISSUE TITLE
Get CometFlexVoting under the size limit

### ISSUE THREAD

**Issue by davidlaprade** [ScopeLift/flexible-voting#47]
It's currently ~8kB over the limit[^0]. As part of this, let's also bring back the size check in CI which as removed in https://github.com/ScopeLift/flexible-voting/pull/46#discussion_r1195532129

To fix we probably want to:
* extend Comet to redefine `updateBasePrincipal`, note that this function will need to call internal functions that we do not have the space to include in Comet -- namely `FlexVotingClient._checkpointRawBalanceOf`! Need to figure out how to do this (e.g. maybe make the function external but with a modifier that only allows the Comet instance to call it?)
* create a new Comet constructor that stores the governor address
* extend Comet to add the storage vars in `FlexVotingClient`. This might be a little tricky because some of them reference types in libraries like OZ's Checkpoints and we cannot afford to import them:
  ```solidity
  mapping(uint256 => mapping(address => bool)) private proposalVotersHasVoted;

  /// @notice Map proposalId to vote totals expressed on this proposal.
  mapping(uint256 => ProposalVote) public proposalVotes;

  /// @notice Mapping from address to stored (not rebased) balance checkpoint history.
  mapping(address => Checkpoints.History) private balanceCheckpoints;

  /// @notice History of total stored (not rebased) balances.
  Checkpoints.History internal totalDepositCheckpoints;
  ```
* extend `CometExt` with the remaining logic we need

[^0]: ![image](https://github.com/ScopeLift/flexible-voting/assets/7997618/d47af580-6470-4abe-bef3-581220f63dbb)

**Comment by alexkeating** [comment]
We moved these contract to https://github.com/ScopeLift/flexible-voting-clients
