### ISSUE TITLE
Linear Inference Approach to AToken Snapshotting

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/flexible-voting#9]
At the time of making a snapshot (i.e. a balance changing due to a transfer, mint, etc...), record the balanceOf *before* (pre balance) the relevant event takes place and after (post balance).

When calculating vote weight, look at the closest "post balance" entry recorded before the proposal time, and the closest "pre balance" entry recorded after the proposal time, and linearly infer a balance between them. If there is no entry recorded after the proposal was submitted (because the user has not take any actions since the proposal was created), look at the balanceOf value at the time of the weight being looked up, and use this as the second point in the linear inference.

Pros:

* Maybe simpler than #8
* Maybe cheaper (gas) than #8

Cons:

* Not exact: total weight could be > or < 100%, and this must be accounted for

**Comment by wildmolasses** [comment]
it seems the `snapshot[]` length could be arbitrarily long. would it make sense to use binary search on the snapshots when calculating vote weights?

**Comment by apbendi** [comment]
Hey @wildmolasses, just a note that I edited the description above a bit to make it a little clearer (hopefully).

> it seems the snapshot[] length could be arbitrarily long. would it make sense to use binary search on the snapshots when calculating vote weights? or is there a better way?

Don't remember off the top of my head but I think our existing snapshotting code (borrowed from ERC20Votes) does this?

**Comment by davidlaprade** [comment]
I think we can close this now that #21 has merged. Feel free to re-open if I'm wrong here!
